#!/bin/bash
R=""
# Port number as Argument
if [ $# -eq 0 ]
  then
    R="45454"
  else
    R=$1
fi

echo "Starting mynetwork"
docker network create -d bridge mynetwork
echo "Starting dataDock Volume"
docker run -v /data/ --name dataDock jayantmalani/data:latest bin/bash
echo "Starting Server Container"
docker run -d --net=mynetwork --volumes-from dataDock --name catserver jayantmalani/server:latest python Server.py /data/string.txt $R 
echo "Starting Client Container"
docker run --net=mynetwork --volumes-from dataDock --name catclient jayantmalani/client:latest python client.py /data/string.txt $R
docker logs catclient > log
#verifying if the logs are correct
if grep -vq OK "log"; then
    echo "Failed, Please check Server Client configuration"
else
    echo "Passed"
fi
echo "Cleaning up"
# Clean up
docker stop catserver
docker stop catclient
docker stop dataDock
docker rm catserver
docker rm catclient
docker rm dataDock
docker network rm mynetwork
rm log
echo "Deleting log"
